# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- release
- devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX=g++-4.9
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
