# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r:
- release
#- devel

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # R
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update -qq

install: 
  # R
  - sudo apt-get install r-base r-base-dev gfortran
  - sudo apt-get install libudunits2-dev
  - sudo Rscript -e 'install.packages(c("igraph", "knitr", "rmarkdown", "testthat", "tidygraph", "RcppProgress", "RcppArmadillo", "ggraph"), repos = "http://cran.r-project.org")'
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
